spring:
  liquibase:
    change-log: classpath:common_webtest_data.xml
    password: root
    url: jdbc:postgresql://localhost:31666/postgres
    user: postgres
    enabled: true
  http:
    encoding:
      enabled: true
      force: true
